info:
  name: micro-admin
  version: 0.0.0
  description: Boilerplate for Microservice Admin in Java
  documentation: https://github.com/javaboilerplates/micro-admin
server:
  port: 8002
security:
  user:
    name: admin
    password: admin
spring:
  boot:
    admin:
      username: ${security.user.name}
      password: ${security.user.password}
      url: http://localhost:${server.port}
      client:
        metadata:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
  application:
    name: micro-admin

